on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Find Flags
    environment:
      name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: find_flags
        with:
          project: support-service
          environment: dano
        env:
          LAUNCHDARKLY_ACCESS_TOKEN: ${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
